/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/skull/ornate_book.glb 
Author: N8 (https://sketchfab.com/nathanmlange)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ornate-book-f55f8ffd11ef48629962d0f178039849
Title: Ornate Book
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Book(props) {
  const { nodes, materials } = useGLTF("/models/book/ornate_book.glb");

  const ref = useRef();
  useFrame(() => {
    if (ref.current) {
      // Change these values to adjust the rotation speed and axis
      ref.current.rotation.x += 0.01;
      ref.current.rotation.y += 0.01;
    }
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-275.852, -86.223, -351.945]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["02___Default"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/book/ornate_book.glb");
